### PR TITLE
Update tell.a.rhyme.dialog

### PR DESCRIPTION
**Pull request by KathyReid**
This was flagged by user Jos Knippen, who has been doing a lot of Dutch translations - both the 'prooving' and the ellipses instead of periods.

### CODE REVIEW

**Comment by forslund** [comment]
Should the .'s after "nightingale birds" be updated as well?

**Comment by penrods** [comment]
The "prooving" was intentional at the time -- the original Mimic didn't pronounce "proving" very well, so the misspelling got the pronunciation correct.  Probably should have a comment about this, but I'd rather have it spoken properly, as the author worked hard on the flow.

**Comment by penrods** [comment]
> Should the .'s after "nightingale birds" be updated as well?

I think the phrase "nightingale birds" is appropriate -- it is plural, not a possessive.

**Comment by forslund** [comment]
I meant the ellipsis characters.

**Comment by KathyReid** [comment]
The author has penned a poem most fine; 
We merely seek to syntactically refine: 
An ellipsis here, pronunciation there - 
Not to impugn such a delicate rhyme :-) 

---

Just to wrap a ribbon around this one - are we agreed on the following actions: 

* We change the ellipsis after `nightingale birds`
* We leave `prooving` to accommodate `mimic` pronunciation
* The other changes we leave in place

Best, Kathy

**Comment by forslund** [comment]
Sounds good to me!

**Comment by forslund** [comment]
I'm closing this one for the time being as we're shutting down the 18.08 branch

**Pull request closed without merging**
